{"descriptive_stats": {}, "hypothesis_tests": {}, "correlations": {}, "reliability_metrics": {}, "error": "An error occurred during analysis: \"None of [Index(['{virtue}_score', '{vice}_score'], dtype='object')] are in the [columns]\""}